kind: Deployment
apiVersion: apps/v1
metadata:
  name: shinyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      project: shiny_demo
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        project: shiny_demo
    spec:
      containers:
      - name: shiny-pod
        imagePullPolicy: Never
        ports:
        - containerPort: 3838
        image: shiny_me:0.1
