apiVersion: v1
kind: Pod
metadata:
  name: plumber
  labels:
    name: plumber-pod
    project: shiny_demo
spec:
  containers:
    - name: plumber
      image: plumber_me:0.1
      ports:
        - containerPort: 8000
