apiVersion: v1
kind: Pod
metadata:
  name: plumber
  labels:
    name: plumber-pod
    project: shiny_demo
spec:
  containers:
    - name: plumber
      image: plumber_me:0.1
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: plumber
  labels:
    name: plumber-service
    project: shiny_demo
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    name: plumber-pod
    project: shiny_demo
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: shinyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      project: shiny_demo
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        project: shiny_demo
    spec:
      containers:
        - name: shiny-pod
          imagePullPolicy: Never
          ports:
            - containerPort: 3838
          image: shiny_me:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: svc-local
spec:
  type: NodePort
  ports:
    - port: 3838
      protocol: TCP
      targetPort: 3838
      nodePort: 30001
  selector:
    project: shiny_demo
