apiVersion: v1
kind: Service
metadata:
  name: plumber
  labels:
    name: plumber-service
    project: shiny_demo
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    name: plumber-pod
    project: shiny_demo
